services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
      restart: unless-stopped
      build:
        context: .
        dockerfile: Dockerfile_frontend
      ports:
        - "3000:80"
      depends_on:
        - backend
